services:
  - type: web
    name: crypto-news-server
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
    dockerfilePath: ./Dockerfile
    startCommand: sh -c "chmod +x ./app && ./app"
